spring.application.name=Web01

# Oracle DB ??
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=100.100.109.24:1521
spring.datasource.username=springuser
spring.datasource.password=spring1234!

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# Oracle ?? ??
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#??? ???? 8080?? ??
server.port=8080
# ?? ssl ?? ?? ?? ?? ????(NAS Spring???)
#server.port=8443
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=springboot

