spring.application.name=Web01

# ? DBeaver "ORCLPDB1 springuser" ??? ??
spring.datasource.url=jdbc:oracle:thin:@//100.100.109.24:1521/ORCLPDB1
spring.datasource.username=springuser
# spring.datasource.password  ? secret?? ??

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
# Oracle ?? ??
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ? Nginx ??? ??? ?? ?? (HTTPS ????? ???? ??)
server.forward-headers-strategy=framework

#??? ???? 8080?? ??
server.port=8080
# ?? ssl ?? ?? ?? ?? ????(NAS Spring???)
#server.port=8443
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=springboot

# Gmail ? ???? ??: Google ?? ? ?? ? 2?? ?? ? ? ????
# Gmail ?? (?? SMTP? ?? ??)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=royalkjungho@gmail.com
# Gmail ? ???? # ? ?? ???? X, ? ???? O
# spring.mail.password  ? secret?? ??
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ? secret ?? import (??? ?? ? ? ? optional)
spring.config.import=optional:classpath:application-secret.properties



