# SQL ?? (??? ???? ??)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ?? ??
spring.jpa.properties.hibernate.format_sql=true

# ??? ?????? ??
app.upload.path=${APP_UPLOAD_PATH}
app.upload.url-prefix=${APP_UPLOAD_URL_PREFIX}