-- ============================================================
-- V10 : 게시글 읽음 이력 (사용자별 읽음 상태 기기 간 동기화)
-- ============================================================

CREATE SEQUENCE POST_READS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE POST_READS (
    ID         NUMBER    PRIMARY KEY,
    POST_ID    NUMBER    NOT NULL,
    USER_ID    NUMBER    NOT NULL,
    READ_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_READS_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(ID)  ON DELETE CASCADE,
    CONSTRAINT FK_READS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)  ON DELETE CASCADE,
    CONSTRAINT UQ_READS      UNIQUE (POST_ID, USER_ID)  -- 동일 사용자의 중복 기록 방지
);

CREATE INDEX IDX_POST_READS_USER_ID ON POST_READS(USER_ID);
CREATE INDEX IDX_POST_READS_POST_ID ON POST_READS(POST_ID);
