-- ============================================================
-- V14 : 공지 관리
-- ============================================================

CREATE SEQUENCE NOTICES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE NOTICES (
    ID          NUMBER        DEFAULT NOTICES_SEQ.NEXTVAL PRIMARY KEY,
    AUTHOR_ID   NUMBER        NOT NULL,
    TITLE       VARCHAR2(200) NOT NULL,
    CONTENT     CLOB,
    SORT_ORDER  NUMBER        DEFAULT 0 NOT NULL,   -- 낮을수록 상단 노출
    ACTIVE      NUMBER(1,0)   DEFAULT 1 NOT NULL,   -- 1: 노출 / 0: 숨김
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_NOTICE_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_NOTICES_SORT ON NOTICES(ACTIVE, SORT_ORDER ASC);
