-- ============================================================
-- V16 : 공지-카테고리 다대다 전환
--       기존 단일 CATEGORY_ID 컬럼 → NOTICE_CATEGORIES 조인 테이블
-- ============================================================

-- 기존 FK/인덱스/컬럼 제거
ALTER TABLE NOTICES DROP CONSTRAINT FK_NOTICE_CATEGORY;
DROP INDEX IDX_NOTICES_CATEGORY;
ALTER TABLE NOTICES DROP COLUMN CATEGORY_ID;

-- 조인 테이블 생성
CREATE TABLE NOTICE_CATEGORIES (
    NOTICE_ID   NUMBER NOT NULL,
    CATEGORY_ID NUMBER NOT NULL,
    CONSTRAINT PK_NOTICE_CATEGORIES PRIMARY KEY (NOTICE_ID, CATEGORY_ID),
    CONSTRAINT FK_NC_NOTICE   FOREIGN KEY (NOTICE_ID)   REFERENCES NOTICES(ID)    ON DELETE CASCADE,
    CONSTRAINT FK_NC_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_NC_NOTICE   ON NOTICE_CATEGORIES(NOTICE_ID);
CREATE INDEX IDX_NC_CATEGORY ON NOTICE_CATEGORIES(CATEGORY_ID);
