-- ============================================================
-- V4 : 게시판 카테고리 + 게시글
-- ============================================================

-- ── 카테고리 ────────────────────────────────────────────────
CREATE SEQUENCE CATEGORIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CATEGORIES (
    ID          NUMBER          PRIMARY KEY,
    NAME        VARCHAR2(50)    NOT NULL UNIQUE,
    SORT_ORDER  NUMBER          DEFAULT 0 NOT NULL
);

-- 기본 카테고리 3개
INSERT INTO CATEGORIES (ID, NAME, SORT_ORDER)
VALUES (CATEGORIES_SEQ.NEXTVAL, '자유게시판', 1);

INSERT INTO CATEGORIES (ID, NAME, SORT_ORDER)
VALUES (CATEGORIES_SEQ.NEXTVAL, '공지사항', 2);

INSERT INTO CATEGORIES (ID, NAME, SORT_ORDER)
VALUES (CATEGORIES_SEQ.NEXTVAL, 'Q&A', 3);

-- ── 게시글 ──────────────────────────────────────────────────
CREATE SEQUENCE POSTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE POSTS (
    ID           NUMBER          PRIMARY KEY,
    USER_ID      NUMBER          NOT NULL,
    CATEGORY_ID  NUMBER,
    TITLE        VARCHAR2(200)   NOT NULL,
    CONTENT      CLOB,                               -- Quill.js HTML 내용
    VIEW_COUNT   NUMBER          DEFAULT 0 NOT NULL,
    LIKE_COUNT   NUMBER          DEFAULT 0 NOT NULL,
    CREATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_POSTS_USER     FOREIGN KEY (USER_ID)     REFERENCES USERS(ID),
    CONSTRAINT FK_POSTS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID) ON DELETE SET NULL
);

CREATE INDEX IDX_POSTS_USER_ID     ON POSTS(USER_ID);
CREATE INDEX IDX_POSTS_CATEGORY_ID ON POSTS(CATEGORY_ID);
CREATE INDEX IDX_POSTS_CREATED_AT  ON POSTS(CREATED_AT DESC);