-- ============================================================
-- V5 : 댓글
-- ============================================================

CREATE SEQUENCE COMMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE COMMENTS (
    ID         NUMBER           PRIMARY KEY,
    POST_ID    NUMBER           NOT NULL,
    USER_ID    NUMBER           NOT NULL,
    CONTENT    VARCHAR2(1000)   NOT NULL,
    CREATED_AT TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_COMMENTS_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(ID)    ON DELETE CASCADE,
    CONSTRAINT FK_COMMENTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)    ON DELETE CASCADE
);

CREATE INDEX IDX_COMMENTS_POST_ID ON COMMENTS(POST_ID);
CREATE INDEX IDX_COMMENTS_USER_ID ON COMMENTS(USER_ID);