-- ============================================================
-- V6 : 게시글 좋아요 (중복 방지)
-- ============================================================

CREATE SEQUENCE POST_LIKES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE POST_LIKES (
    ID         NUMBER    PRIMARY KEY,
    POST_ID    NUMBER    NOT NULL,
    USER_ID    NUMBER    NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_LIKES_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LIKES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_LIKES      UNIQUE (POST_ID, USER_ID)  -- 동일 사용자 중복 좋아요 방지
);

CREATE INDEX IDX_POST_LIKES_POST_ID ON POST_LIKES(POST_ID);
CREATE INDEX IDX_POST_LIKES_USER_ID ON POST_LIKES(USER_ID);

-- 좋아요 추가 시 POSTS.LIKE_COUNT 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_LIKES_INSERT
AFTER INSERT ON POST_LIKES
FOR EACH ROW
BEGIN
    UPDATE POSTS SET LIKE_COUNT = LIKE_COUNT + 1 WHERE ID = :NEW.POST_ID;
END;
/

-- 좋아요 삭제 시 POSTS.LIKE_COUNT 자동 감소 트리거
CREATE OR REPLACE TRIGGER TRG_LIKES_DELETE
AFTER DELETE ON POST_LIKES
FOR EACH ROW
BEGIN
    UPDATE POSTS SET LIKE_COUNT = GREATEST(LIKE_COUNT - 1, 0) WHERE ID = :OLD.POST_ID;
END;
/